<?php
/**
 * @file
 * Code for the vesafe_structure feature.
 */

include_once 'vesafe_structure.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * {@inheritdoc}
 */
function vesafe_structure_form_good_practice_node_form_alter(&$form, &$form_state) {
  VeSafeStructureForms::good_practice_node_form_alter($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * {@inheritdoc}
 */
function vesafe_structure_form_key_article_node_form_alter(&$form, &$form_state) {
  VeSafeStructureForms::key_article_node_form_alter($form, $form_state);
}

/**
 * Implements hook_form_alter().
 *
 * {@inheritdoc}
 */
function vesafe_structure_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_exposed_form' && $form['#id'] == 'views-exposed-form-good-practices-admin-view-page') {
    VeSafeStructureForms::good_practice_admin_content_view_form_alter($form, $form_state);
  }
}
